### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NightRaidGamer** [Abokn/Kernel-keylogger#1]
hello I would like to know how I do to see the pressed keys, is there a txt file stored somewhere? I compiled and installed the driver but I'm kind of lost...

**Comment by Abokn** [comment]
Hi, scancodes of the keys are printed out using KdPrint. Compile the driver in debug mode and use something like DebugView to see them.

**Comment by NightRaidGamer** [comment]
> Hi, scancodes of the keys are printed out using KdPrint. Compile the driver in debug mode and use something like DebugView to see them.

hello I loaded the driver and typed some things but when I open the DebugView it doesn't show anything I'm using windows 11 22000.493, could it be the incompatible version of Windows?

**Comment by Abokn** [comment]
Make sure that Capture > Capture Kernel is checked. Also, you may need to create the key "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter"  with a default value of 0xf if it doesn't already exist. You can do executing: `reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter" /V DEFAULT /t REG_DWORD /d 0xf`

**Comment by NightRaidGamer** [comment]
> Make sure that Capture > Capture Kernel is checked. Also, you may need to create the key "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter" with a default value of 0xf if it doesn't already exist. You can do executing: `reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Debug Print Filter" /V DEFAULT /t REG_DWORD /d 0xf`

I did what you said and this appears:

 [*] Starting coupling routine
[+] Successfully obtained a pointer to hidusb
[+] Hidclass driver extension retrieved successfully
[+] Dispatch routine IRP_MJ_INTERNAL_DEVICE_CONTROL connected successfully

but when i type something nothing appears, is there any way to make the driver create a txt file somewhere hidden and save everything there?

**Comment by Abokn** [comment]
In relation to nothing appearing on the screen, this driver just works for HID keyboards connected over USB.
I suppose you are testing the driver in a VM, in that case, by default the VM sees the keyboard as a PS/2 one. You can check if this is the case in the system information program. You should see an element with a description that says Standard PS/2 Keyboard.
![image](https://user-images.githubusercontent.com/99767016/157041160-c6351e42-cbf6-481d-9dfa-01d0969f4aa1.png)
In VMware you can fix this by connecting the keyboard directly to the VM  (right-click to the VM while running, removable devices > "Your Keyboard" >  Connect.
After that the system information program should show something like this:
![image](https://user-images.githubusercontent.com/99767016/157042279-2fda7ee6-3028-47ce-9cec-05c0b85bdd7e.png)
After that, the scancodes should appear. Keep in mind that doing this will disconnect the keyboard from your main machine. To get it back right-click to the VM while running, removable devices > "Your Keyboard" >  Disconnect.

**Comment by NightRaidGamer** [comment]
> In relation to nothing appearing on the screen, this driver just works for HID keyboards connected over USB. I suppose you are testing the driver in a VM, in that case, by default the VM sees the keyboard as a PS/2 one. You can check if this is the case in the system information program. You should see an element with a description that says Standard PS/2 Keyboard. 

I found out what the problem was, I'm not using a vm, my keyboard is HID but not usb is ps2, I put a usb and started receiving in the debug view perfectly, is it possible to add support for ps2 ports?

> If you want to save the scancodes to a file, they are displayed in the InsertScanCodes function in ProcessReports.cpp. So, you could store them in a buffer and periodically write that buffer to a certain file.

so I'm kind of new to programming, could you tell me step by step, what do I have to add/remove in ProcessReports.cpp please? for ex: I want the driver to create a hidden DumpStack.txt in C:\Windows\System32 and save everything there...

**Comment by NightRaidGamer** [comment]
> > In relation to nothing appearing on the screen, this driver just works for HID keyboards connected over USB. I suppose you are testing the driver in a VM, in that case, by default the VM sees the keyboard as a PS/2 one. You can check if this is the case in the system information program. You should see an element with a description that says Standard PS/2 Keyboard.
> 
> I found out what the problem was, I'm not using a vm, my keyboard is HID but not usb is ps2, I put a usb and started receiving in the debug view perfectly, is it possible to add support for ps2 ports?
> 
> > If you want to save the scancodes to a file, they are displayed in the InsertScanCodes function in ProcessReports.cpp. So, you could store them in a buffer and periodically write that buffer to a certain file.
> 
> so i'm new to programming, could you tell me step by step, what do I have to add/remove in ProcessReports.cpp please? for ex: I want the driver to create a hidden DumpStack.txt in C:\Windows\System32 and save everything there...

**Comment by NightRaidGamer** [comment]
> > > In relation to nothing appearing on the screen, this driver just works for HID keyboards connected over USB. I suppose you are testing the driver in a VM, in that case, by default the VM sees the keyboard as a PS/2 one. You can check if this is the case in the system information program. You should see an element with a description that says Standard PS/2 Keyboard.
> > 
> > 
> > I found out what the problem was, I'm not using a vm, my keyboard is HID but not usb is ps2, I put a usb and started receiving in the debug view perfectly, is it possible to add support for ps2 ports?
> > > If you want to save the scancodes to a file, they are displayed in the InsertScanCodes function in ProcessReports.cpp. So, you could store them in a buffer and periodically write that buffer to a certain file.
> > 

> > so i'm new to programming, could you tell me step by step, what do I have to add/remove in ProcessReports.cpp please? for ex: I want the driver to create a hidden DumpStack.txt in C:\Windows\System32 and save everything there...

**Comment by NightRaidGamer** [comment]
> > > > In relation to nothing appearing on the screen, this driver just works for HID keyboards connected over USB. I suppose you are testing the driver in a VM, in that case, by default the VM sees the keyboard as a PS/2 one. You can check if this is the case in the system information program. You should see an element with a description that says Standard PS/2 Keyboard.

 I found out what the problem was, I'm not using a vm, my keyboard is HID but not usb is ps2, I put a usb and started receiving in the debug view perfectly, is it possible to add support for ps2 ports?
>  If you want to save the scancodes to a file, they are displayed in the InsertScanCodes function in ProcessReports.cpp. So, you could store them in a buffer and periodically write that buffer to a certain file.
> 
so i'm new to programming, could you tell me step by step, what do I have to add/remove in ProcessReports.cpp please? for ex: I want the driver to create a hidden DumpStack.txt in C:\Windows\System32 and save everything there...

**Comment by Abokn** [comment]
> I found out what the problem was, I'm not using a vm, my keyboard is HID but not usb is ps2, I put a usb and started receiving in the debug view perfectly, is it possible to add support for ps2 ports?

Sadly, PS/2 keyboards are handled in a different way and can't be hooked with this method.

>so I'm kind of new to programming, could you tell me step by step, what do I have to add/remove in ProcessReports.cpp please?

I can't tell just exactly how to do it. You can just look at other keyloggers and see how do they handle it.

**Comment by NightRaidGamer** [comment]
@Abokn thanks for all the help
